events.o: events.c ../local/include/vcfio.h ../local/include/dsvio.h \
  ../local/include/biolibc.h ../local/include/biostring.h events.h \
  events-protos.h haploh-vcf-depths-protos.h
	${CC} -c ${CFLAGS} events.c

haploh-vcf-depths.o: haploh-vcf-depths.c ../local/include/vcfio.h \
  ../local/include/dsvio.h ../local/include/biolibc.h \
  ../local/include/biostring.h haploh-vcf-depths.h events.h \
  events-protos.h haploh-vcf-depths-protos.h
	${CC} -c ${CFLAGS} haploh-vcf-depths.c

