events.o: events.c events.h events-protos.h
	${CC} -c ${CFLAGS} events.c

haploh-median-depths.o: haploh-median-depths.c ../local/include/vcfio.h \
  ../local/include/vcfio-protos.h \
  ../local/include/chromosome-name-cmp-protos.h ../local/include/tsvio.h \
  ../local/include/tsvio-protos.h haploh-median-depths.h events.h \
  events-protos.h haploh-median-depths-protos.h
	${CC} -c ${CFLAGS} haploh-median-depths.c

